apiVersion: v2
appVersion: 2.5.2
description: A Helm chart for the Splunk Operator for Kubernetes
maintainers:
- email: vivekr@splunk.com
  name: Vivek Reddy
- email: akondur@splunk.com
  name: Arjun Kondur
name: splunk-operator
type: application
version: 2.5.2
